language: c
sudo: true
addons:
  apt:
    packages:
    - ksh
    - libgd2-xpm-dev
    - tcl-dev
    - libdevil-dev
    - libpango1.0-dev
    - libxaw7-dev
    - freeglut3-dev
    - colorgcc
    - libgd-dev
    - cmake
    - cmake-data

services:
- docker

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=TRUE

  matrix:
    - DOCKER_BUILD=FALSE
      BUILD_SYSTEM=autotools

    - DOCKER_BUILD=FALSE
      BUILD_SYSTEM=cmake

    - DOCKER_BUILD=TRUE
      BUILD_SYSTEM=autotools

    - DOCKER_BUILD=TRUE
      BUILD_SYSTEM=cmake


install:
# Enable colored gcc output
- export CC=colorgcc
# Install unit testing framework Criterion.
- cd dependencies/criterion
- mkdir build
- cd build
- cmake ..
- cmake --build .
- sudo make install
- sudo ldconfig
- cd ${TRAVIS_BUILD_DIR}
- if [ ${DOCKER_BUILD} == "TRUE" ] ; then docker build -t centos7-build-env ci/centos7/ ; fi

script:
- cd ${TRAVIS_BUILD_DIR}
- if [ ${DOCKER_BUILD} == "FALSE" ] ; then sudo ./ci/${BUILD_SYSTEM}-build_and_test.sh ; fi
- if [ ${DOCKER_BUILD} == "TRUE" ] ; then docker run --rm -v `pwd`:/graphviz -w /graphviz -i -t centos7-build-env bash "ci/${BUILD_SYSTEM}-build_and_test.sh" ; fi

before_deploy:
- export DEPLOYED_FILE=$(ls *.tar.gz)
- echo "deploying ${DEPLOYED_FILE} to GitHub releases"
- sudo chown travis ${DEPLOYED_FILE}

# If no tag is set, deploy as nightly
- if [ !${TRAVIS_TAG} ] ; then export TRAVIS_TAG=Nightly ; fi

deploy:
  provider: releases
  api_key:
    secure: JZzPstqKB4y7biMytFw6RZHxz57S+uolXonZrYCqE7UiVnVrBfRRGbFemvDq7a5lvBfM4KS3ODO05hjk82sXW3fGxrJAVWCVZ4kf31VWFG0aLEJnDso09bkCcNdvs7w1MkZWde0RM6Ux0mtN4Y9EE6goaRt1rEPVBKZ3hBNQBtDTGWf9FjNE4rhC14a9+Cvf/LTD+1cka/R/4A2P4eXcdAOQhZyu7CgsRrssY69PJxWVt3yznjtLBZZrNuaVkNO2QwJWBV3k1bVvWqApOYdKzz/Dh6q+EuuV85kXmdJJS4/KrS4eRXk3Aj4wadTGyh+bDhfJKIqqo59U86Nu+kuR4msPNbnUxbgMBobaw51SP8yFtHWY3FwQLVdepcFV8SuMXv9ebBUXLte0XLyq7GxFTFS5p7NMpS35t+NaM0Ijw4aYpKleBXAKlS8Cdxp1CjsW+3aMCxa4y0O1jCC1XoVAP4AyUaRfpckjHyu6tailklUl9ychcSS6WaZXbnJgHfirDoMXmcQH+8KPA5vPRKdkY0HVV9KLfC9bN5QbjsBSIalUPIwkbX8MYvKeJIltpWb7zmdE7NnMmCvnjXeRNw6IzjrICnIJuxbS1389mFwOOS1Jj/YFbPrG3XWF8wmtjlAube3nmwkEJOCPSFf6cG5Aw96KhMRrjeCZgWBLdZ9/kxw=
  skip_cleanup: true
  file: "${DEPLOYED_FILE}"
  on:
    repo: caozhilong/MOTHBALLED-graphviz
    condition: ${DOCKER_BUILD} == "FALSE" && ${BUILD_SYSTEM} == "autotools"
